openapi: 3.0.3
info:
  title: Task API
  version: 1.0.0
  description: API for managing tasks

servers:
  - url: https://api.example.com/v1

paths:
  /tasks:
    get:
      summary: Get all tasks
      operationId: getTasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{taskId}:
    get:
      summary: Get a task by ID
      operationId: getTaskById
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    patch:
      summary: Update a task by ID
      operationId: updateTask
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    delete:
      summary: Delete a task by ID
      operationId: deleteTask
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted
        '404':
          description: Task not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          example: '123'
        title:
          type: string
          example: 'Finish documentation'
        description:
          type: string
          example: 'Write OpenAPI docs for the Task API'
        status:
          type: string
          enum: [pending, in_progress, completed]
          example: 'pending'
        due_date:
          type: string
          format: date-time
          example: '2025-09-11T23:00:00.000Z'
        created:
          type: string
          format: date-time
          example: '2025-09-11T23:00:00.000Z'
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        due_date:
          type: string
          format: datetime
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [pending, in_progress, completed]
        due_date:
          type: string
          format: date-time
          example: '2025-09-11T23:00:00.000Z'
